CREATE DATABASE THAT
go
USE THAT

CREATE TABLE _USER(
	user_phone VARCHAR(64) PRIMARY KEY,
	user_name NVARCHAR(50) NOT NULL,
	user_email VARCHAR(50) NOT NULL,
	user_password VARCHAR(60) NOT NULL,
	user_role BIT NOT NULL
);

CREATE TABLE BILL(
	bill_id INT IDENTITY(1000,1) PRIMARY KEY,
	bill_address NVARCHAR(255) NOT NULL,
	bill_date DATE NOT NULL,
	bill_status BIT NOT NULL,
	bill_note NVARCHAR(255) NULL,
	user_phone VARCHAR(64) REFERENCES _USER(user_phone) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL
);

CREATE TABLE PRODUCER(
	producer_id VARCHAR(30) PRIMARY KEY,
	producer_email VARCHAR(50) NOT NULL,
	producer_name NVARCHAR(50) NOT NULL,
	producer_phone VARCHAR(11) NOT NULL,
);

CREATE TABLE CATEGORY(
	category_id VARCHAR(10) PRIMARY KEY,
	category_name VARCHAR(50) NOT NULL,
);

CREATE TABLE PRODUCT(
	product_id VARCHAR(20) PRIMARY KEY,
	product_name NVARCHAR(50) NOT NULL,
	product_quantity INT NOT NULL CHECK(product_quantity >= 0),
	product_price FLOAT NOT NULL CHECK(product_price >= 0),
	category_id VARCHAR(10) REFERENCES CATEGORY(category_id) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	producer_id VARCHAR(30) REFERENCES PRODUCER(producer_id) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
);

CREATE TABLE IMAGE(
	image_link VARCHAR(255) PRIMARY KEY,
	product_id VARCHAR(20) REFERENCES PRODUCT(product_id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,	
);

CREATE TABLE BILL_DETAIL(
	bill_id INT REFERENCES BILL(bill_id) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	product_id VARCHAR(20) REFERENCES PRODUCT(product_id) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	PRIMARY KEY(product_id,bill_id),
	bill_detail_price FLOAT NOT NULL CHECK(bill_detail_price > 0),
	bill_detail_amount INT NOT NULL CHECK(bill_detail_amount > 0)
);

CREATE TABLE SPEC(
	spec_id INT IDENTITY(100,1) PRIMARY KEY,
	spec_key NVARCHAR(20) NOT NULL,
	spec_value NVARCHAR(50) NOT NULL,
);

CREATE TABLE SPEC_DETAIL(
	spec_id INT REFERENCES SPEC(spec_id) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	product_id VARCHAR(20) REFERENCES PRODUCT(product_id) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	PRIMARY KEY(spec_id,product_id)
);
