package com.tinhocanhtrang.entity;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * BillDetailId generated by hbm2java
 */
@Embeddable
public class BillDetailId implements java.io.Serializable {

	private String productId;
	private int billId;

	public BillDetailId() {
	}

	public BillDetailId(String productId, int billId) {
		this.productId = productId;
		this.billId = billId;
	}

	@Column(name = "product_id", nullable = false, length = 20)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "bill_id", nullable = false)
	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BillDetailId))
			return false;
		BillDetailId castOther = (BillDetailId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
				&& (this.getBillId() == castOther.getBillId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + this.getBillId();
		return result;
	}

}
