package com.tinhocanhtrang.entity;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * BillDetail generated by hbm2java
 */
@Entity
@Table(name = "BILL_DETAIL", schema = "dbo", catalog = "THAT")
public class BillDetail implements java.io.Serializable {

	private BillDetailId id;
	private Bill bill;
	private Product product;
	private double billDetailPrice;
	private int billDetailAmount;

	public BillDetail() {
	}

	public BillDetail(BillDetailId id, Bill bill, Product product, double billDetailPrice, int billDetailAmount) {
		this.id = id;
		this.bill = bill;
		this.product = product;
		this.billDetailPrice = billDetailPrice;
		this.billDetailAmount = billDetailAmount;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false, length = 20)),
			@AttributeOverride(name = "billId", column = @Column(name = "bill_id", nullable = false)) })
	public BillDetailId getId() {
		return this.id;
	}

	public void setId(BillDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bill_id", nullable = false, insertable = false, updatable = false)
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "bill_detail_price", nullable = false, precision = 53, scale = 0)
	public double getBillDetailPrice() {
		return this.billDetailPrice;
	}

	public void setBillDetailPrice(double billDetailPrice) {
		this.billDetailPrice = billDetailPrice;
	}

	@Column(name = "bill_detail_amount", nullable = false)
	public int getBillDetailAmount() {
		return this.billDetailAmount;
	}

	public void setBillDetailAmount(int billDetailAmount) {
		this.billDetailAmount = billDetailAmount;
	}

}
