package com.tinhocanhtrang.entity;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "BILL", schema = "dbo", catalog = "THAT")
public class Bill implements java.io.Serializable {

	private Integer billId;
	private User user;
	private Serializable billAddress;
	private Date billDate;
	private boolean billStatus;
	private Serializable billNote;
	private Set<BillDetail> billDetails = new HashSet<BillDetail>(0);

	public Bill() {
	}

	public Bill(User user, Serializable billAddress, Date billDate, boolean billStatus) {
		this.user = user;
		this.billAddress = billAddress;
		this.billDate = billDate;
		this.billStatus = billStatus;
	}

	public Bill(User user, Serializable billAddress, Date billDate, boolean billStatus, Serializable billNote,
			Set<BillDetail> billDetails) {
		this.user = user;
		this.billAddress = billAddress;
		this.billDate = billDate;
		this.billStatus = billStatus;
		this.billNote = billNote;
		this.billDetails = billDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bill_id", unique = true, nullable = false)
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_phone", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "bill_address", nullable = false)
	public Serializable getBillAddress() {
		return this.billAddress;
	}

	public void setBillAddress(Serializable billAddress) {
		this.billAddress = billAddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "bill_date", nullable = false, length = 10)
	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	@Column(name = "bill_status", nullable = false)
	public boolean isBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(boolean billStatus) {
		this.billStatus = billStatus;
	}

	@Column(name = "bill_note")
	public Serializable getBillNote() {
		return this.billNote;
	}

	public void setBillNote(Serializable billNote) {
		this.billNote = billNote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<BillDetail> getBillDetails() {
		return this.billDetails;
	}

	public void setBillDetails(Set<BillDetail> billDetails) {
		this.billDetails = billDetails;
	}

}
