package com.tinhocanhtrang.entity;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.ToString;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "IMAGE", schema = "dbo", catalog = "THAT")
@ToString
public class Image  {

	private String imageLink;
	private Product product;

	public Image() {
	}

	public Image(String imageLink, Product product) {
		this.imageLink = imageLink;
		this.product = product;
	}

	@Id

	@Column(name = "image_link", unique = true, nullable = false)
	public String getImageLink() {
		return this.imageLink;
	}

	public void setImageLink(String imageLink) {
		this.imageLink = imageLink;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
