package com.tinhocanhtrang.entity;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.annotations.Nationalized;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Producer generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "PRODUCER", schema = "dbo", catalog = "THAT")
public class Producer {

	private String producerId;
	private String producerEmail;
	private String producerName;
	private String producerPhone;
	private List<Product> products;

	public Producer(String producerId, String producerEmail, String producerName, String producerPhone) {
		this.producerId = producerId;
		this.producerEmail = producerEmail;
		this.producerName = producerName;
		this.producerPhone = producerPhone;
	}

	@Id
	@Column(name = "producer_id", unique = true, nullable = false, length = 30)
	public String getProducerId() {
		return this.producerId;
	}

	public void setProducerId(String producerId) {
		this.producerId = producerId;
	}

	@Column(name = "producer_email", nullable = false, length = 50)
	public String getProducerEmail() {
		return this.producerEmail;
	}

	public void setProducerEmail(String producerEmail) {
		this.producerEmail = producerEmail;
	}

	@Column(name = "producer_name", nullable = false)
	@Nationalized
	public String getProducerName() {
		return this.producerName;
	}

	public void setProducerName(String producerName) {
		this.producerName = producerName;
	}

	@Column(name = "producer_phone", nullable = false, length = 11)
	public String getProducerPhone() {
		return this.producerPhone;
	}

	public void setProducerPhone(String producerPhone) {
		this.producerPhone = producerPhone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producer")
	public List<Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
