package com.tinhocanhtrang.entity;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;
// Generated Jun 8, 2023, 11:31:01 PM by Hibernate Tools 4.3.6.Final
import java.util.List;
import org.hibernate.annotations.Nationalized;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Spec generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Entity
@Table(name = "SPEC", schema = "dbo", catalog = "THAT")
public class Spec  {

	private Integer specId;
	private String specKey;
	private String specValue;
	private List<Product> products;


	public Spec(String specKey, String specValue) {
		this.specKey = specKey;
		this.specValue = specValue;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "spec_id", unique = true, nullable = false)
	public Integer getSpecId() {
		return this.specId;
	}

	public void setSpecId(Integer specId) {
		this.specId = specId;
	}

	@Column(name = "spec_key", nullable = false)
	public String getSpecKey() {
		return this.specKey;
	}

	public void setSpecKey(String specKey) {
		this.specKey = specKey;
	}

	@Column(name = "spec_value", nullable = false)
	public String getSpecValue() {
		return this.specValue;
	}

	public void setSpecValue(String specValue) {
		this.specValue = specValue;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SPEC_DETAIL", schema = "dbo", catalog = "THAT", joinColumns = {
			@JoinColumn(name = "spec_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "product_id", nullable = false, updatable = false) })
	public List<Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
